version: '3'

services:
  bridge0:
    container_name: bridge0
    image: "ghcr.io/celestiaorg/celestia-node:sha-042ebe1"
    environment:
      - NODE_TYPE=bridge
      - CELESTIA_CUSTOM=ephemeral:02EED4BCFAF0CC8A3D1100D588E571FBF44219488F01AB48870BC9015A9F105A
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.0:26657",
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge0/nodekey0:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.1.0

  bridge1:
    container_name: bridge1
    image: "ghcr.io/celestiaorg/celestia-node:v0.2.0"
    environment:
      - NODE_TYPE=bridge
      - CELESTIA_CUSTOM=ephemeral:02EED4BCFAF0CC8A3D1100D588E571FBF44219488F01AB48870BC9015A9F105A
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.1:26657",
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge1/nodekey1:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.1.1

  bridge2:
    container_name: bridge2
    image: "ghcr.io/celestiaorg/celestia-node:v0.2.0"
    environment:
      - NODE_TYPE=bridge
      - CELESTIA_CUSTOM=ephemeral:02EED4BCFAF0CC8A3D1100D588E571FBF44219488F01AB48870BC9015A9F105A
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.2:26657",
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge2/nodekey2:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.1.2

networks:
  localnet:
    name: localnet
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
