version: '3'

services:
  dalc0:
    container_name: dalc0
    image: "ghcr.io/celestiaorg/celestia-node:sha-042ebe1"
    environment:
      - NODE_TYPE=light
      - MY_VAL_ADDRESS=celes1dm7fp7uwrr5y68v48gg8jhd2cku7vt7f4l8w0s
      - CELESTIA_CUSTOM=ephemeral:02EED4BCFAF0CC8A3D1100D588E571FBF44219488F01AB48870BC9015A9F105A
    command: [
            "celestia", "light",
            "--node.store", "/dalc",
            "start",
            "--headers.trusted-peers",
            "/ip4/192.167.1.0/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw",
             ]
    volumes:
       - ${PWD}/dalc/celestia-app/keyring-test/:/root/keyring-test/:ro
       - ${PWD}/dalc/optimint_server.toml:/dalc/optimint_server.toml
       - ${PWD}/dalc/celestia-light/data/LOCK:/dalc/data/LOCK
       - ${PWD}/dalc/celestia-light/config.toml:/dalc/config.toml
       - ${PWD}/dalc/celestia-light/keys/OAZHALLLMV4Q:/dalc/keys/OAZHALLLMV4Q

    networks:
      localnet:
        ipv4_address: 192.167.3.0

networks:
  localnet:
    name: localnet
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
