[Core]
  IP = "192.167.10.0"
  RPCPort = "0"
  GRPCPort = "0"

[State]
  KeyringAccName = ""

[P2P]
  ListenAddresses = ["/ip4/0.0.0.0/udp/2121/quic", "/ip6/::/udp/2121/quic", "/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
  AnnounceAddresses = []
  NoAnnounceAddresses = ["/ip4/0.0.0.0/udp/2121/quic", "/ip4/127.0.0.1/tcp/2121/quic", "/ip6/::/udp/2121/quic", "/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
  Bootstrapper = false
  MutualPeers = []
  PeerExchange = false
  RoutingTableRefreshPeriod = "1m0s"
  [P2P.ConnManager]
    Low = 50
    High = 100
    GracePeriod = "1m0s"

[RPC]
  Address = "0.0.0.0"
  Port = "26658"

[Gateway]
  Address = ""
  Port = ""
  Enabled = false

[Share]
  PeersLimit = 3
  DiscoveryInterval = "30s"
  AdvertiseInterval = "30s"

[Header]
  TrustedHash = "1D0BC6EFA758E94AC6519F8747A07E8E0CBBF3FBC8D9FFE684C22A863803BF27"
  TrustedPeers = []
  [Header.Store]
    StoreCacheSize = 4096
    IndexCacheSize = 16384
    WriteBatchSize = 2048
  [Header.Server]
    WriteDeadline = "5s"
    ReadDeadline = "1m0s"
    MaxRequestSize = 512
